import type { MealPlanResponse, GroceryCategory, BudgetSummary } from './types';

// ─── Meal Plan as Plain Text (DETAILED) ───
export function mealPlanToText(plan: MealPlanResponse): string {
  const lines: string[] = [];

  lines.push('══════════════════════════════════════════════════');
  lines.push('       LUTONG TIPID — Weekly Meal Plan');
  lines.push('══════════════════════════════════════════════════');
  lines.push('');
  lines.push(`📅 Budget:      ₱${plan.budget_summary.weekly_budget.toLocaleString()}`);
  lines.push(`👨‍👩‍👧‍👦 Family Size: ${plan.family_size} tao`);
  lines.push(`📍 Region:      ${plan.region}`);
  lines.push(`💰 Total Cost:  ₱${plan.budget_summary.total_estimated_cost.toLocaleString()}`);
  lines.push(`💵 Remaining:   ₱${plan.budget_summary.remaining_budget.toLocaleString()}`);
  lines.push(`📊 Utilization: ${plan.budget_summary.weekly_budget > 0 ? Math.round((plan.budget_summary.total_estimated_cost / plan.budget_summary.weekly_budget) * 100) : 0}%`);
  lines.push('');

  for (const day of plan.days) {
    lines.push('══════════════════════════════════════════════════');
    lines.push(`  📆 ${day.day.toUpperCase()}  —  Daily Total: ₱${day.daily_cost.toLocaleString()}`);
    lines.push('══════════════════════════════════════════════════');
    lines.push('');

    for (const meal of day.meals) {
      const type = meal.meal_type.charAt(0).toUpperCase() + meal.meal_type.slice(1);
      lines.push(`  ┌─ ${type.toUpperCase()} ────────────────────────────`);
      lines.push(`  │ 🍽️  ${meal.dish_name}`);
      lines.push(`  │     ${meal.description}`);
      lines.push(`  │`);
      lines.push(`  │ 💰 Cost: ₱${meal.estimated_cost}  ⏱️ Cook time: ${meal.cook_time_minutes} min`);

      // Nutrition
      if (meal.nutrition_estimate) {
        const n = meal.nutrition_estimate;
        lines.push(`  │ 📊 Nutrition: ${n.calories} cal | Protein: ${n.protein} | Carbs: ${n.carbs} | Fat: ${n.fat}`);
      }

      // Ingredients
      if (meal.ingredients && meal.ingredients.length > 0) {
        lines.push(`  │`);
        lines.push(`  │ 🧾 Ingredients:`);
        for (const ing of meal.ingredients) {
          lines.push(`  │   • ${ing.name} — ${ing.quantity} (₱${ing.estimated_cost})`);
        }
      }

      lines.push(`  └──────────────────────────────────────`);
      lines.push('');
    }
  }

  // Grocery list summary
  if (plan.grocery_list && plan.grocery_list.length > 0) {
    lines.push('══════════════════════════════════════════════════');
    lines.push('       🛒 GROCERY LIST');
    lines.push('══════════════════════════════════════════════════');
    lines.push('');
    for (const cat of plan.grocery_list) {
      lines.push(`  📦 ${cat.category}`);
      for (const item of cat.items) {
        lines.push(`     - ${item.name}: ${item.quantity} — ₱${item.estimated_cost}`);
      }
      lines.push('');
    }
  }

  // Tips
  if (plan.tips && plan.tips.length > 0) {
    lines.push('──────────────────────────────────────────────────');
    lines.push('💡 Tips ni Lutong Tipid:');
    for (const tip of plan.tips) {
      lines.push(`  • ${tip}`);
    }
    lines.push('');
  }

  lines.push('══════════════════════════════════════════════════');
  lines.push('  Generated by Lutong Tipid AI 🍳');
  lines.push(`  Date: ${new Date().toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('══════════════════════════════════════════════════');

  return lines.join('\n');
}

// ─── Grocery List as Plain Text (optimized for Viber/Messenger paste) ───
export function groceryListToText(
  groceryList: GroceryCategory[],
  budgetSummary: BudgetSummary
): string {
  const lines: string[] = [];

  lines.push('🛒 GROCERY LIST — Lutong Tipid');
  lines.push(`Budget: ₱${budgetSummary.weekly_budget.toLocaleString()}`);
  lines.push('');

  for (const cat of groceryList) {
    const subtotal = cat.items.reduce((s, i) => s + i.estimated_cost, 0);
    lines.push(`📦 ${cat.category} (₱${Math.round(subtotal)})`);
    for (const item of cat.items) {
      lines.push(`  - ${item.name}: ${item.quantity} — ₱${item.estimated_cost}`);
    }
    lines.push('');
  }

  const total = groceryList.reduce(
    (s, c) => s + c.items.reduce((ss, i) => ss + i.estimated_cost, 0),
    0
  );
  lines.push(`💰 TOTAL: ₱${Math.round(total).toLocaleString()}`);
  lines.push(`📊 Budget remaining: ₱${Math.round(budgetSummary.remaining_budget).toLocaleString()}`);

  return lines.join('\n');
}

// ─── Meal Plan as CSV (DETAILED with ingredients per row) ───
export function mealPlanToCsv(plan: MealPlanResponse): string {
  const rows: string[][] = [];

  rows.push([
    'Day', 'Meal Type', 'Dish Name', 'Description',
    'Meal Cost (PHP)', 'Cook Time (min)',
    'Calories', 'Protein', 'Carbs', 'Fat',
    'Ingredient', 'Quantity', 'Ingredient Cost (PHP)',
  ]);

  for (const day of plan.days) {
    for (const meal of day.meals) {
      if (meal.ingredients.length === 0) {
        // Row with no ingredients
        rows.push([
          day.day, meal.meal_type, meal.dish_name, meal.description,
          String(meal.estimated_cost), String(meal.cook_time_minutes),
          String(meal.nutrition_estimate?.calories ?? ''),
          meal.nutrition_estimate?.protein ?? '',
          meal.nutrition_estimate?.carbs ?? '',
          meal.nutrition_estimate?.fat ?? '',
          '', '', '',
        ]);
      } else {
        // One row per ingredient, meal info on first row
        for (let i = 0; i < meal.ingredients.length; i++) {
          const ing = meal.ingredients[i];
          if (i === 0) {
            rows.push([
              day.day, meal.meal_type, meal.dish_name, meal.description,
              String(meal.estimated_cost), String(meal.cook_time_minutes),
              String(meal.nutrition_estimate?.calories ?? ''),
              meal.nutrition_estimate?.protein ?? '',
              meal.nutrition_estimate?.carbs ?? '',
              meal.nutrition_estimate?.fat ?? '',
              ing.name, ing.quantity, String(ing.estimated_cost),
            ]);
          } else {
            rows.push([
              '', '', '', '', '', '', '', '', '', '',
              ing.name, ing.quantity, String(ing.estimated_cost),
            ]);
          }
        }
      }
    }
  }

  return rows.map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(',')).join('\n');
}

// ─── Grocery List as CSV ───
export function groceryListToCsv(groceryList: GroceryCategory[]): string {
  const rows: string[][] = [];

  rows.push(['Category', 'Item', 'Quantity', 'Estimated Cost (PHP)']);

  for (const cat of groceryList) {
    for (const item of cat.items) {
      rows.push([cat.category, item.name, item.quantity, String(item.estimated_cost)]);
    }
  }

  return rows.map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(',')).join('\n');
}

// ─── Download helpers ───
export function downloadText(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  triggerDownload(blob, filename);
}

export function downloadCsv(content: string, filename: string): void {
  const bom = '\uFEFF'; // UTF-8 BOM for Excel compatibility
  const blob = new Blob([bom + content], { type: 'text/csv;charset=utf-8' });
  triggerDownload(blob, filename);
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Print-friendly view (DETAILED with ingredients) ───
export function printMealPlan(plan: MealPlanResponse): void {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Lutong Tipid — Meal Plan</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', sans-serif; padding: 24px; color: #1B4332; font-size: 11px; line-height: 1.4; }
    h1 { font-size: 22px; margin-bottom: 4px; color: #1B4332; }
    .header { margin-bottom: 16px; border-bottom: 3px solid #D4A843; padding-bottom: 10px; }
    .meta { color: #555; font-size: 11px; margin-top: 4px; }
    .budget-bar { display: flex; gap: 20px; background: #eaf5ee; border-radius: 6px; padding: 8px 12px; margin-bottom: 16px; font-size: 12px; font-weight: 600; }

    .day-section { margin-bottom: 16px; page-break-inside: avoid; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; }
    .day-header { background: #2D6A4F; color: white; padding: 6px 12px; font-size: 13px; font-weight: bold; display: flex; justify-content: space-between; }
    .meals-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1px; background: #eee; }
    .meal-card { background: white; padding: 10px; }
    .meal-type { font-size: 9px; text-transform: uppercase; color: #957520; font-weight: bold; letter-spacing: 0.5px; margin-bottom: 2px; }
    .dish-name { font-weight: bold; font-size: 12px; color: #1B4332; margin-bottom: 2px; }
    .dish-desc { font-size: 10px; color: #666; font-style: italic; margin-bottom: 4px; }
    .meal-meta { font-size: 10px; color: #555; margin-bottom: 4px; }
    .cost-badge { display: inline-block; background: #D4A843; color: white; border-radius: 4px; padding: 1px 6px; font-size: 10px; font-weight: bold; }
    .nutrition { font-size: 9px; color: #777; margin-bottom: 4px; }

    .ingredients-title { font-size: 9px; font-weight: bold; color: #2D6A4F; text-transform: uppercase; margin-bottom: 2px; }
    .ingredient { font-size: 10px; color: #444; padding-left: 8px; }
    .ingredient::before { content: "• "; color: #2D6A4F; }
    .ing-cost { color: #957520; font-weight: 600; }

    .grocery-section { margin-top: 20px; page-break-before: auto; }
    .grocery-section h2 { font-size: 16px; color: #1B4332; border-bottom: 2px solid #2D6A4F; padding-bottom: 4px; margin-bottom: 10px; }
    .grocery-cat { margin-bottom: 10px; }
    .grocery-cat-name { font-weight: bold; font-size: 11px; color: #2D6A4F; margin-bottom: 3px; }
    .grocery-item { font-size: 10px; padding-left: 12px; color: #444; }

    .tips-section { margin-top: 16px; background: #FDF8EB; border-left: 4px solid #D4A843; padding: 10px 14px; border-radius: 0 6px 6px 0; }
    .tips-section h3 { font-size: 12px; color: #957520; margin-bottom: 6px; }
    .tip { font-size: 10px; color: #555; margin-bottom: 3px; padding-left: 12px; }

    .summary { margin-top: 16px; padding: 10px 14px; background: #eaf5ee; border-radius: 6px; font-size: 12px; }
    .footer { margin-top: 16px; text-align: center; color: #999; font-size: 9px; }

    @media print {
      body { padding: 12px; }
      .day-section { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🍳 Lutong Tipid — Weekly Meal Plan</h1>
    <div class="meta">
      Budget: ₱${plan.budget_summary.weekly_budget.toLocaleString()} |
      Family: ${plan.family_size} tao |
      Region: ${plan.region} |
      Generated: ${new Date().toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
    </div>
  </div>

  <div class="budget-bar">
    <span>💰 Total: ₱${plan.budget_summary.total_estimated_cost.toLocaleString()}</span>
    <span>💵 Remaining: ₱${plan.budget_summary.remaining_budget.toLocaleString()}</span>
    <span>📊 ${plan.budget_summary.weekly_budget > 0 ? Math.round((plan.budget_summary.total_estimated_cost / plan.budget_summary.weekly_budget) * 100) : 0}% used</span>
  </div>

  ${plan.days.map(day => `
    <div class="day-section">
      <div class="day-header">
        <span>${day.day}</span>
        <span>₱${day.daily_cost.toLocaleString()}</span>
      </div>
      <div class="meals-grid">
        ${day.meals.map(meal => `
          <div class="meal-card">
            <div class="meal-type">${meal.meal_type}</div>
            <div class="dish-name">${meal.dish_name}</div>
            <div class="dish-desc">${meal.description}</div>
            <div class="meal-meta">
              <span class="cost-badge">₱${meal.estimated_cost}</span>
              ⏱️ ${meal.cook_time_minutes} min
            </div>
            ${meal.nutrition_estimate ? `
              <div class="nutrition">
                ${meal.nutrition_estimate.calories} cal | P: ${meal.nutrition_estimate.protein} | C: ${meal.nutrition_estimate.carbs} | F: ${meal.nutrition_estimate.fat}
              </div>
            ` : ''}
            ${meal.ingredients.length > 0 ? `
              <div class="ingredients-title">Ingredients:</div>
              ${meal.ingredients.map(ing => `
                <div class="ingredient">${ing.name} — ${ing.quantity} <span class="ing-cost">(₱${ing.estimated_cost})</span></div>
              `).join('')}
            ` : ''}
          </div>
        `).join('')}
      </div>
    </div>
  `).join('')}

  ${plan.grocery_list && plan.grocery_list.length > 0 ? `
    <div class="grocery-section">
      <h2>🛒 Grocery List</h2>
      ${plan.grocery_list.map(cat => `
        <div class="grocery-cat">
          <div class="grocery-cat-name">${cat.category}</div>
          ${cat.items.map(item => `
            <div class="grocery-item">${item.name}: ${item.quantity} — ₱${item.estimated_cost}</div>
          `).join('')}
        </div>
      `).join('')}
    </div>
  ` : ''}

  ${plan.tips && plan.tips.length > 0 ? `
    <div class="tips-section">
      <h3>💡 Tips ni Lutong Tipid</h3>
      ${plan.tips.map(tip => `<div class="tip">• ${tip}</div>`).join('')}
    </div>
  ` : ''}

  <div class="summary">
    <strong>Budget Summary:</strong>
    ₱${plan.budget_summary.total_estimated_cost.toLocaleString()} / ₱${plan.budget_summary.weekly_budget.toLocaleString()}
    (₱${plan.budget_summary.remaining_budget.toLocaleString()} remaining)
    — ₱${plan.budget_summary.cost_per_person_per_day.toLocaleString()} per person per day
  </div>

  <div class="footer">
    Generated by Lutong Tipid AI 🍳 — Masarap na ulam, tipid pa!
  </div>
</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 300);
  }
}
